[package]
name = "doors"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy = "0.15"
bevy_embedded_assets = "0.12"
leafwing-input-manager = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
avian2d = "0.2.1"
bevy_lunex = "0.2.4"
petgraph = "0.7.1"
bevy_aseprite_ultra = "0.4.1"
